x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.9.0-python3.12}
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    # For backward compatibility, with Airflow <2.3
    # AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    AIRFLOW_CONFIG: '/opt/airflow/config/config.cfg'
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/sql:/opt/sql
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/datalake:/opt/dbt
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/profile:/opt/dbt/profiles
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/profile:/opt/airflow/.dbt/
    - ./jobs:/opt/airflow/jobs
    # - ${AIRFLOW_PROJ_DIR:-.}/jobs:/opt/airflow/jobs
    # - ./config:/opt/airflow/config
    # - ./dags:/opt/airflow/dags
    # - ./logs:/opt/airflow/logs
    # - ./plugins:/opt/airflow/plugins
    # - ./sql:/opt/sql
    # - ./datalake:/opt/dbt
    # - ./profile:/opt/dbt/profiles
    # - ./profile:/opt/airflow/.dbt/
    # - ./config/airflow.cfg:/opt/airflow/airflow.cfg
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  networks:
    - data-stack

x-spark-common: 
  &spark-common
  image: bitnami/spark:3.5
  build: 
      context: .
      dockerfile: Dockerfile.spark
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - data-stack
services:
# Airflow
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      # Nuevo para SUPERSET
      POSTGRES_MULTIPLE_DATABASES: superset  # Nueva variable
      POSTGRES_MULTIPLE_USERS: superset:superset  # usuario:contraseña
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init-scripts/init-superset-db.sh:/docker-entrypoint-initdb.d/init-superset-db.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - data-stack

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - data-stack

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: webserver
    ports:
      - 9093:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9093/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-stack

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-stack

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    build:
      context: .
      dockerfile: Dockerfile.airflow
    # start
    # tmpfs:
    #   - '/opt/airflow/'
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-stack
      
  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-stack

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    build:
      context: .
      dockerfile: Dockerfile.airflow
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        function ver() {
          printf "%04d%04d%04d%04d" $${1//./ }
        }
        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
        airflow_version_comparable=$$(ver $${airflow_version})
        min_airflow_version=2.9.0
        min_airflow_version_comparable=$$(ver $${min_airflow_version})
        if (( airflow_version_comparable < min_airflow_version_comparable )); then
          echo
          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
          echo
          exit 1
        fi
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/airflow/sources
    networks:
      - data-stack

  airflow-cli:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile.airflow
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow
    networks:
      - data-stack

  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  # or by explicitly targeted on the command line e.g. docker-compose up flower.
  # See: https://docs.docker.com/compose/profiles/
  flower:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: celery flower
    profiles:
      - flower
    ports:
      - "5553:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5553/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# Datalake
  trino:
    container_name: trino
    hostname: trino
    image: 'trinodb/trino:424'
    ports:
      - '8080:8080'
    volumes:
      - ./lake/etc:/usr/lib/trino/etc:ro
      - ./lake/etc/catalog:/etc/trino/catalog
      # - ./plugins:/usr/lib/trino/plugin
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 14G  
    networks:
      - data-stack

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore
    networks:
      - data-stack

  hive-metastore:
    container_name: hive-metastore
    # build:
    #   context: .
    #   dockerfile: Dockerfile.hive
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    # image: 'apache/hive-metastore:3.1.3'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./lake/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    #   - ./lake/conf/tez-site.xml:/opt/tez/conf/tez-site.xml:ro
    environment:
      # DB_TYPE: mysql
      METASTORE_DB_HOSTNAME: mariadb
      # HIVE_EXECUTION_ENGINE: mr 
    depends_on:
      - mariadb
    networks:
      - data-stack

  minio:
    hostname: minio
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      # - /mnt/d/Desarrollo/datalake/data:/data
      - ./lake/data:/data
    environment:
      MINIO_ROOT_USER: josemi
      MINIO_ROOT_PASSWORD: josemi-2024
    command: server /data --console-address ":9001"
    networks:
      - data-stack

# Spark
  spark-master:
    <<: *spark-common
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_MASTER_PORT=7077
      - SPARK_PUBLIC_DNS=spark-master
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      - data-stack

  spark-worker:
    <<: *spark-common
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_PUBLIC_DNS=spark-worker
    ports:
      - "8082:8080"
    networks:
      - data-stack
# Superset
  superset:
    container_name: superset
    image: apache/superset:latest
    build:
      context: .
      dockerfile: Dockerfile.superset
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:superset@postgres/superset
      - SUPERSET_SECRET_KEY=josemi-123  
      - SUPERSET_FAB_ADMIN_USERNAME=admin
      - SUPERSET_FAB_ADMIN_PASSWORD=superset
      - SUPERSET_FAB_ADMIN_EMAIL=admin@superset.com
      - _PIP_ADDITIONAL_REQUIREMENTS=sqlalchemy-trino psycopg2-binary pymysql
    volumes:
      - ./viz/superset_data:/app/superset_home
      - ./viz/superset:/app/pythonpath
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data-stack

  superset-init:
    container_name: superset-init
    image: apache/superset:latest
    build: 
      context: .
      dockerfile: Dockerfile.superset
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./init-scripts/superset-init.sh:/app/superset-init.sh
      - ./viz/superset_data:/app/superset_home
    command: ["bash", "/app/superset-init.sh"]
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:superset@postgres/superset
      - SUPERSET_SECRET_KEY=josemi-123
    networks:
      - data-stack

volumes:
  postgres-db-volume:
  superset_data:

  minio-data:
    driver: local

networks:
  data-stack:
    driver: bridge
    name: data-stack